sudo: false
dist: trusty

addons:
  chrome: stable

language: node_js
node_js:
  - "10"

branches:
  only:
    - master
    - beta
    - release
    - auto
    - /^greenkeeper.*$/
    - bisect

cache:
  yarn: true
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bower's cache

jobs:
  fail_fast: true

  include:

    - env: NAME=test # used only to make Travis UI show description

before_install:
  # prevent the npm loading indicator
  - npm config --global set spin false

  # travis currently includes yarn v0.17.8 (20170705)
  # this isn't new enough for our use of --non-interactive
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

script:
  - yarn test:slow
