sudo: false

language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - node

cache:
  directories:
    $HOME/.npm
    $HOME/.cache # includes bowers cache

before_install:
  - npm config set spin false

install:
  - node --version
  - npm --version
  - git --version
  - npm install --no-optional

script: npm run-script test-all:cover

after_script:
  - npm install coveralls codeclimate-test-reporter
  - cat coverage/lcov.info | codeclimate
  - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
