sudo: false

language: node_js
node_js:
  - "0.12"
  - "4"
  - "6"
  - "7"

branches:
  only:
    - master
    - beta
    - release
    - auto
    - /^greenkeeper.*$/

cache:
  yarn: true
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bower's cache

env:
  - NPM_SCRIPT=test-all:cover

matrix:
  fast_finish: true
  include:
  - node_js: "6"
    env: SIMULATE_EMBER_CLI_BETA=true NPM_SCRIPT=test

before_install:
  # Once we no longer support Node.js 0.12 we can drop this entire section.
  # prevent the npm loading indicator
  - npm config --global set spin false
  # if npm version is less than 3.0.0, upgrade to 3
  - if [[ $(npm -v | cut -d '.' -f 1) -lt 3 ]]; then npm i -g npm@^3; fi

script:
  # For now we will use `npm` to kick off the test suite.
  # Can switch to `yarn` once we no longer support Node.js 0.12:
  # - yarn run test-all:cover
  - npm run-script test-all:cover
  - npm run-script $NPM_SCRIPT

after_success:
  # For now we will use `npm` for globals.
  # Can switch to `yarn` once we no longer support Node.js 0.12:
  # - travis_retry yarn global add coveralls codeclimate-test-reporter
  - travis_retry npm install -g coveralls codeclimate-test-reporter
  - cat coverage/lcov.info | codeclimate-test-reporter
  - cat coverage/lcov.info | coveralls
  - .travis/deploy.sh
